name: auto-approve
description: auto approve
runs:
  using: composite
  steps:
    - name: Install bun
      uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
      with:
        aqua_version: v2.62.2
      env:
        AQUA_CONFIG: ${{github.action_path}}/aqua/aqua.yaml
    - run: bun run index.ts
      id: check
      shell: bash
      working-directory: ${{github.action_path}}
      env:
        AQUA_CONFIG: ${{github.action_path}}/aqua/aqua.yaml
        # pull-requests:read is required to list the updated files
        GITHUB_TOKEN: ${{github.token}}
        PULL_REQUEST_NUMBER: ${{github.event.pull_request.number}}
        PATH_PREFIXES: staging/
    - name: Get PAT from AWS Secrets Manager
      if: steps.check.outputs.ok == 'true'
      id: token
      shell: bash
      run: echo "get"
    - name: Approve
      if: steps.check.outputs.ok == 'true'
      run: echo "approve"
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
