---
name: test
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # To checkout this pull request
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - run: echo hello

  approve:
    uses: szksh-lab-2/test-auto-approve/.github/workflows/auto_approve.yaml@auto-approve
    needs: test
    permissions:
      contents: read
      pull-requests: read
